version: '3'
services:
  dynamodb:
    image: amazon/dynamodb-local
    ports:
    - "8000:8000"
  kinesis:
#    image: dlsniper/kinesalite
    image: instructure/kinesalite
    ports:
    - "4567:4567"
    environment:
      - AWS_CBOR_DISABLE=true